language: python
python:
    - 3.4
sudo: required
before_install:
    - git clone https://github.com/proycon/LaMachine
    - cd LaMachine
    - bash virtualenv-bootstrap.sh
install: 
    - python setup.py install
script: 
    - ./test.sh
